/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialCardRouteImport } from './routes/testimonial-card'
import { Route as ProfileCardRouteImport } from './routes/profile-card'
import { Route as BlogCardRouteImport } from './routes/blog-card'
import { Route as IndexRouteImport } from './routes/index'

const TestimonialCardRoute = TestimonialCardRouteImport.update({
  id: '/testimonial-card',
  path: '/testimonial-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCardRoute = ProfileCardRouteImport.update({
  id: '/profile-card',
  path: '/profile-card',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCardRoute = BlogCardRouteImport.update({
  id: '/blog-card',
  path: '/blog-card',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog-card': typeof BlogCardRoute
  '/profile-card': typeof ProfileCardRoute
  '/testimonial-card': typeof TestimonialCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog-card': typeof BlogCardRoute
  '/profile-card': typeof ProfileCardRoute
  '/testimonial-card': typeof TestimonialCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog-card': typeof BlogCardRoute
  '/profile-card': typeof ProfileCardRoute
  '/testimonial-card': typeof TestimonialCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog-card' | '/profile-card' | '/testimonial-card'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog-card' | '/profile-card' | '/testimonial-card'
  id: '__root__' | '/' | '/blog-card' | '/profile-card' | '/testimonial-card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogCardRoute: typeof BlogCardRoute
  ProfileCardRoute: typeof ProfileCardRoute
  TestimonialCardRoute: typeof TestimonialCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonial-card': {
      id: '/testimonial-card'
      path: '/testimonial-card'
      fullPath: '/testimonial-card'
      preLoaderRoute: typeof TestimonialCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-card': {
      id: '/profile-card'
      path: '/profile-card'
      fullPath: '/profile-card'
      preLoaderRoute: typeof ProfileCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-card': {
      id: '/blog-card'
      path: '/blog-card'
      fullPath: '/blog-card'
      preLoaderRoute: typeof BlogCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogCardRoute: BlogCardRoute,
  ProfileCardRoute: ProfileCardRoute,
  TestimonialCardRoute: TestimonialCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
